name: "Rubocop v2"

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  # schedule:
  #   - cron: $cron-weekly

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --version 0.6.1 --skip-install

      - name: Install dependencies
        run: bundle install

      - name: Rubocop run
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "
      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rubocop.sarif